version: '3.8'

services:
  nards_db_backup:
    image: nards/nards-db-backup:latest
    build: .
    environment:
      DB_HOST: 'database'
      DB_PORT: '5432' # postgres/postgis: 5432; mysql: 3306
      DB_USER: 'user'
      DB_PASSWORD: 'password'
      DB_TYPE: 'postgres' # postgres/postgis/mysql
      BACKUP_DIR: /backups
      CRON_CONFIGS: '[{"cron": "0 * * * *", "retention_max": 15, "name": "every"},{"cron": "0 * * * *", "retention_max": 1, "name": "hourly"}]'
      # RESTORE_CONFIG_NAME: 'hourly'
    volumes:
      - ./backups:/backups
