version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testuser
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    expose:
       - 3306
    volumes:
      - ./tests/init_mysql.sql:/docker-entrypoint-initdb.d/init_mysql.sql

  nards_db_backup:
    build: .
    command:
      - "pytest"
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=test_user
      - DB_USER=test_user
      - DB_PASSWORD=test_password
    depends_on:
      - mysql
