version: '3.8'

services:
  postgis:
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5432:5432"

  nards_db_backup:
    build: .
    environment:
      - DB_TYPE=postgres
      - DB_HOST=postgis
      - DB_PORT=5432
      - DB_NAME=test_db
      - DB_USER=test_user
      - DB_PASSWORD=test_password
      - BACKUP_FREQUENCY=* * * * *  # Every minute for testing
      - BACKUP_DIR=/backups
      - MAX_BACKUPS=5  # Adjust for testing
      - MAX_MONTHLY_BACKUPS=2  # Adjust for testing
    depends_on:
      - postgis
    volumes:
      - ./backups:/backups
