services:
  test-runner:
    build: .
    command: pytest -q
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/app
    environment:
      DB_HOST_MYSQL: mysql
      DB_PORT_MYSQL: "3306"
      DB_USER_MYSQL: test_user
      DB_PASSWORD_MYSQL: test_password
      DB_NAME_MYSQL: test_database
      DB_HOST_POSTGRES: postgres
      DB_PORT_POSTGRES: "5432"
      DB_USER_POSTGRES: test_user
      DB_PASSWORD_POSTGRES: test_password
      DB_NAME_POSTGRES: test_database
      DB_HOST_POSTGIS: postgis
      DB_PORT_POSTGIS: "5432"
      DB_USER_POSTGIS: test_user
      DB_PASSWORD_POSTGIS: test_password
      DB_NAME_POSTGIS: test_database
      MYSQL_SSL_MODE: "DISABLED"
      PG_RESTORE_CLEAN: "true"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test_database
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
       - "13306:3306"
    command:
      - --default-authentication-plugin=mysql_native_password

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: test_database
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "15432:5432"

  postgis:
    image: postgis/postgis:14-3.5
    environment:
      POSTGRES_DB: test_database
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5432:5432"
    volumes:
      - ./tests/init_postgis.sql:/docker-entrypoint-initdb.d/init_postgis.sql

  nards_backup_mysql:
    build: .
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: testuser
      DB_PASSWORD: testpassword
      DB_TYPE: mysql
      BACKUP_DIR: /backups
      CRON_CONFIGS: '[{"cron": "* * * * *", "retention_max": 7, "name": "mysql_backup"}]'
      RESTORE_CONFIG_NAME: 'mysql_backup'
    ports:
      - "5001:5000"
    volumes:
      - ./backups:/backups
    depends_on:
      - mysql

  nards_backup_postgis:
    build: .
    environment:
      DB_HOST: postgis
      DB_PORT: 5432
      DB_USER: testuser
      DB_PASSWORD: testpassword
      DB_TYPE: postgis
      BACKUP_DIR: /backups
      CRON_CONFIGS: '[{"cron": "* * * * *", "retention_max": 15, "name": "every"},{"cron": "0 * * * *", "retention_max": 1, "name": "hourly"}]'
      RESTORE_CONFIG_NAME: 'every'
    ports:
      - "5002:5000"
    expose:
      - 5000
    volumes:
      - ./backups:/backups
    depends_on:
      - postgis
