version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testuser
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3306"
    volumes:
      - ./tests/init_mysql.sql:/docker-entrypoint-initdb.d/init_mysql.sql

  postgis:
    image: postgis/postgis:14-3.5
    environment:
      POSTGRES_DB: testuser
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
    ports:
      - "5432:5432"
    volumes:
      - ./tests/init_postgis.sql:/docker-entrypoint-initdb.d/init_postgis.sql

  nards_backup_mysql:
    build: .
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: testuser
      DB_PASSWORD: testpassword
      DB_TYPE: mysql
      BACKUP_DIR: /backups
      CRON_CONFIGS: '[{"cron": "* * * * *", "retention_max": 7, "name": "mysql_backup"}]'
      RESTORE_CONFIG_NAME: 'mysql_backup'
    ports:
      - "5001:5000"
    volumes:
      - ./backups:/backups
    depends_on:
      - mysql

  nards_backup_postgis:
    build: .
    environment:
      DB_HOST: postgis
      DB_PORT: 5432
      DB_USER: testuser
      DB_PASSWORD: testpassword
      DB_TYPE: postgis
      BACKUP_DIR: /backups
      CRON_CONFIGS: '[{"cron": "* * * * *", "retention_max": 15, "name": "every"},{"cron": "0 * * * *", "retention_max": 1, "name": "hourly"}]'
      RESTORE_CONFIG_NAME: 'every'
    ports:
      - "5002:5000"
    expose:
      - 5000
    volumes:
      - ./backups:/backups
    depends_on:
      - postgis

  redis:
    image: redis:7
    ports:
      - "6379:6379" # Potrebbe essere necessario cambiare se la porta host 6379 è già usata

  nards_backup_redis:
    build: .
    environment:
      DB_HOST: redis
      DB_PORT: 6379
      DB_TYPE: redis
      # DB_USER, DB_PASSWORD, DB_MAINTENANCE_NAME non sono tipicamente usati per Redis con questo setup.
      BACKUP_DIR: /backups
      CRON_CONFIGS: '[{"cron": "* * * * *", "retention_max": 5, "name": "redis_backup"}]'
      # RESTORE_CONFIG_NAME: 'redis_backup' # Abilitare per testare il ripristino all'avvio.
      # CONTAINER_NAME: "docker-compose-test-yml_redis_1" # Impostare se si vuole che RedisModule usi un nome container specifico per `docker cp`.
                                                          # Il servizio `nards_backup_redis` deve avere accesso al socket Docker.
    ports:
      - "5003:5000" # Porta host diversa per evitare conflitti.
    volumes:
      - ./backups:/backups
      - /var/run/docker.sock:/var/run/docker.sock # Necessario se RedisModule (in esecuzione in questo container) deve eseguire `docker cp`.
    depends_on:
      - redis
