name: CI Pipeline

on:
  push:
    branches: [ 11-test-automation-pipeline-temp ]
  pull_request:
    branches: [ 11-test-automation-pipeline-temp ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run tests with Docker Compose
      run: docker-compose -f docker-compose.test.yml up --build --exit-code-from test-runner
